# Example config file

label: NEC-dev
env_class: catch
env_name: "Catcher-Level0-v0"
estimator: &estimator catch_conv
seed: 43
cuda: &cuda false
profiling: no
report_freq: &report_freq 256

training:
  step_no: &step_no 512000
  batch_size: &batch_size 32
  update_freq: &update_freq no
  n_horizon: &n_horizon 16
  fast_lr: &fast_lr 0.1
  slow_lr: &slow_lr .00000635

agent:
  name: "nec"
  rescale: no # where required
  epsilon: 0.05
  experience_replay: 5000
  dnd:
    size: 5000
    knn_no: 5
    linear_projection: 32
  cuda: *cuda
  estimator: *estimator
  n_horizon: *n_horizon
  update_freq: *update_freq
  batch_size: *batch_size
  report_freq: *report_freq
  fast_lr: *fast_lr
  slow_lr: *slow_lr

evaluator:
  eval_steps: 2400
  eval_eps: 1000
  eval_interval: 100000
  eval_start: 100000
  estimator: *estimator
  cuda: *cuda
