# Example config file

label: Pong-dev
env_class: atari
env_name: "PongDeterministic-v0"
estimator: &estimator atari_conv
seed: 43
cuda: &cuda false
profiling: no
report_freq: &report_freq 16

training:
  step_no: &step_no 512000
  batch_size: &batch_size 32
  update_freq: &update_freq 16
  n_horizon: &n_horizon 100
  lr: &lr .0000635

agent:
  name: "nec"
  rescale: [84, 84] # where required
  epsilon: 0.2
  experience_replay: 50000
  dnd:
    size: 50000
    knn_no: 50
    linear_projection: 64
  cuda: *cuda
  estimator: *estimator
  n_horizon: *n_horizon
  update_freq: *update_freq
  batch_size: *batch_size
  report_freq: *report_freq
  lr: *lr

evaluator:
  eval_steps: 2400
  eval_eps: 1000
  eval_interval: 100000
  eval_start: 100000
  estimator: *estimator
  cuda: *cuda
